### ISSUE TITLE
Force Dice should show count of LS and DS, not difference

### ISSUE THREAD

**Issue by kewilli** [PeterAntal/Rollo#1]
Currently, the Force die has negative values for DS pips and positive values for LS pips. So a value of "1" means that one more LS pip was rolled than DS. I think it would instead be useful to have the count of each kind listed separately.

**Comment by kewilli** [comment]
But that's, just, like, my opinion, man.

**Comment by PeterAntal** [comment]
Hah, Quite right, shows how much I'd been using the force when I wrote that - Agreed, they shouldn't cancel out.

I'm changing light and dark sides to be tracked as distinct dimensions.
![image](https://user-images.githubusercontent.com/172160/62275175-3d1abd00-b3f6-11e9-8282-5001eccd3d34.png)

**Comment by kewilli** [comment]
May the Force be with you.
